.

diff --git a/server-bin/turnin b/server-bin/turnin
--- a/server-bin/turnin
+++ b/server-bin/turnin
@@ -16,6 +16,18 @@ END
   echo $result
 }
 
+if [ $# -lt 2 ]; then
+  echo "Usage: $0 assignment@class file1 file2 ..."
+  exit 1
+fi
+
+for f in "${@:2}"; do
+  if [ ! -f $f ]; then
+    echo "Error: $f is not a file."
+    exit 1
+  fi
+done
+
 # class-assignment-username.zip
 
 user=$(whoami)
@@ -26,15 +38,9 @@ files="${@:2}"
 
 # turn in the assignment
 
-if [ $# -ge 2 ]; then
-  rm -rf ~/.autogradertmp
-  mkdir ~/.autogradertmp
-  cp $files ~/.autogradertmp
-  cd ~/.autogradertmp
-  zip $user-$class-$assignment.zip *
-  finish-turnin $user-$class-$assignment.zip $class $assignment
-else
-  echo "Usage: $0 assignment@class file1 file2 ..."
-  exit 1
-fi
-
+rm -rf ~/.autogradertmp
+mkdir ~/.autogradertmp
+cp $files ~/.autogradertmp
+cd ~/.autogradertmp
+zip $user-$class-$assignment.zip *
+finish-turnin $user-$class-$assignment.zip $class $assignment
